version: "3"
# Add your custom configuration here.
# See README.md for examples.
services:

  feel:
    volumes:
      - ./logs:/home/feel/feel/logs

  db:
    volumes:
      - ./data_postgres:/var/lib/postgresql/data
